# -*- coding: utf-8 -*-
"""Assignment5_CNN_DNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmMRBgHrcNNI3TP1haL98b6pg6ZwJDTs

# WEEK 5 – DATA 5600
## Assignment #5: CNN and DNN for Image Classification
**Pol Monné Parera (L30170743)**  
pmonneparera@lewisu.edu  
Spring 2026

### 1. Imports
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Sequential
from tensorflow.keras.callbacks import EarlyStopping

np.random.seed(42)
tf.random.set_seed(42)

print(f"TensorFlow version: {tf.__version__}")

"""### 2. Load and Preprocess CIFAR-10"""

# Load CIFAR-10
(x_train_raw, y_train_raw), (x_test_raw, y_test_raw) = keras.datasets.cifar10.load_data()

print(f"Train shape: {x_train_raw.shape}, Test shape: {x_test_raw.shape}")
print(f"CIFAR-10 classes: airplane(0), automobile(1), bird(2), cat(3), deer(4),")
print(f"                  dog(5), frog(6), horse(7), ship(8), truck(9)")

CLASS_NAMES = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

# Binary mapping: vehicles (0,1,8,9) -> 1, animals (2,3,4,5,6,7) -> 0
VEHICLE_CLASSES = {0, 1, 8, 9}

def make_binary(y):
    return (np.isin(y.flatten(), list(VEHICLE_CLASSES))).astype(np.float32)

y_train_bin = make_binary(y_train_raw)
y_test_bin = make_binary(y_test_raw)

print(f"\nBinary label distribution (train): animals={np.sum(y_train_bin==0)}, vehicles={np.sum(y_train_bin==1)}")

# Normalize to [0, 1]
x_train_norm = x_train_raw.astype('float32') / 255.0
x_test_norm = x_test_raw.astype('float32') / 255.0

# For DNN: flatten to 3072-dim vector
x_train_flat = x_train_norm.reshape(len(x_train_norm), -1)
x_test_flat = x_test_norm.reshape(len(x_test_norm), -1)

print(f"DNN input shape: {x_train_flat.shape}")
print(f"CNN input shape: {x_train_norm.shape}")

# Visualize a few samples
fig, axes = plt.subplots(2, 10, figsize=(14, 3))
for i in range(10):
    idx_animal = np.where(y_train_bin == 0)[0][i]
    axes[0, i].imshow(x_train_raw[idx_animal])
    axes[0, i].set_title(CLASS_NAMES[y_train_raw[idx_animal][0]], fontsize=7)
    axes[0, i].axis('off')

    idx_vehicle = np.where(y_train_bin == 1)[0][i]
    axes[1, i].imshow(x_train_raw[idx_vehicle])
    axes[1, i].set_title(CLASS_NAMES[y_train_raw[idx_vehicle][0]], fontsize=7)
    axes[1, i].axis('off')

axes[0, 0].set_ylabel('Animal\nsamples', fontsize=8)
axes[1, 0].set_ylabel('Vehicle\nsamples', fontsize=8)
plt.suptitle('CIFAR-10 Sample Images (Animals row 1, Vehicles row 2)', fontsize=10)
plt.tight_layout()
plt.savefig('cifar10_samples.png', dpi=120, bbox_inches='tight')
plt.show()

"""### 3. DNN Model"""

def build_dnn(input_dim):
    model = Sequential([
        layers.Input(shape=(input_dim,)),
        layers.Dense(512, activation='relu'),
        layers.Dropout(0.4),
        layers.Dense(256, activation='relu'),
        layers.Dropout(0.4),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.3),
        layers.Dense(1, activation='sigmoid')
    ], name='DNN')
    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model

dnn = build_dnn(input_dim=3072)
dnn.summary()

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

dnn_history = dnn.fit(
    x_train_flat, y_train_bin,
    batch_size=128,
    epochs=50,
    validation_split=0.1,
    callbacks=[early_stop],
    verbose=1
)

# DNN training curves
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

ax1.plot(dnn_history.history['accuracy'], label='Train')
ax1.plot(dnn_history.history['val_accuracy'], label='Validation')
ax1.set_title('DNN Accuracy')
ax1.set_xlabel('Epoch'); ax1.set_ylabel('Accuracy')
ax1.legend(); ax1.grid(True)

ax2.plot(dnn_history.history['loss'], label='Train')
ax2.plot(dnn_history.history['val_loss'], label='Validation')
ax2.set_title('DNN Loss')
ax2.set_xlabel('Epoch'); ax2.set_ylabel('Binary Cross-Entropy')
ax2.legend(); ax2.grid(True)

plt.tight_layout()
plt.savefig('dnn_training_curves.png', dpi=120, bbox_inches='tight')
plt.show()
print("Saved: dnn_training_curves.png")

# DNN evaluation
dnn_probs = dnn.predict(x_test_flat, verbose=0).flatten()
dnn_preds = (dnn_probs >= 0.5).astype(int)
dnn_acc = accuracy_score(y_test_bin, dnn_preds)

print(f"DNN Test Accuracy: {dnn_acc * 100:.2f}%")
print()
print(classification_report(y_test_bin, dnn_preds, target_names=['Animal', 'Vehicle']))

"""### 4. CNN Model"""

def build_cnn(input_shape):
    model = Sequential([
        layers.Input(shape=input_shape),

        # Block 1
        layers.Conv2D(32, (3, 3), activation='relu', padding='same'),
        layers.BatchNormalization(),
        layers.Conv2D(32, (3, 3), activation='relu', padding='same'),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Dropout(0.25),

        # Block 2
        layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        layers.BatchNormalization(),
        layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Dropout(0.25),

        # Classifier head
        layers.Flatten(),
        layers.Dense(256, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(1, activation='sigmoid')
    ], name='CNN')
    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model

cnn = build_cnn(input_shape=(32, 32, 3))
cnn.summary()

early_stop_cnn = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

cnn_history = cnn.fit(
    x_train_norm, y_train_bin,
    batch_size=64,
    epochs=50,
    validation_split=0.1,
    callbacks=[early_stop_cnn],
    verbose=1
)

# CNN training curves
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

ax1.plot(cnn_history.history['accuracy'], label='Train')
ax1.plot(cnn_history.history['val_accuracy'], label='Validation')
ax1.set_title('CNN Accuracy')
ax1.set_xlabel('Epoch'); ax1.set_ylabel('Accuracy')
ax1.legend(); ax1.grid(True)

ax2.plot(cnn_history.history['loss'], label='Train')
ax2.plot(cnn_history.history['val_loss'], label='Validation')
ax2.set_title('CNN Loss')
ax2.set_xlabel('Epoch'); ax2.set_ylabel('Binary Cross-Entropy')
ax2.legend(); ax2.grid(True)

plt.tight_layout()
plt.savefig('cnn_training_curves.png', dpi=120, bbox_inches='tight')
plt.show()
print("Saved: cnn_training_curves.png")

# CNN evaluation
cnn_probs = cnn.predict(x_test_norm, verbose=0).flatten()
cnn_preds = (cnn_probs >= 0.5).astype(int)
cnn_acc = accuracy_score(y_test_bin, cnn_preds)

print(f"CNN Test Accuracy: {cnn_acc * 100:.2f}%")
print()
print(classification_report(y_test_bin, cnn_preds, target_names=['Animal', 'Vehicle']))

"""### 5. Confusion Matrices"""

def plot_confusion_matrix(y_true, y_pred, title, ax):
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Animal', 'Vehicle'],
                yticklabels=['Animal', 'Vehicle'],
                ax=ax)
    ax.set_xlabel('Predicted label')
    ax.set_ylabel('True label')
    ax.set_title(title)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4))
plot_confusion_matrix(y_test_bin, dnn_preds, f'DNN Accuracy: {dnn_acc*100:.2f}%', ax1)
plot_confusion_matrix(y_test_bin, cnn_preds, f'CNN Accuracy: {cnn_acc*100:.2f}%', ax2)
plt.tight_layout()
plt.savefig('confusion_matrices.png', dpi=120, bbox_inches='tight')
plt.show()
print("Saved: confusion_matrices.png")

"""### 6. Summary Comparison"""

summary = pd.DataFrame({
    'Model': ['DNN', 'CNN'],
    'Input': ['Flat 3072-dim', '32×32×3 image'],
    'Parameters': [dnn.count_params(), cnn.count_params()],
    'Test Accuracy': [f"{dnn_acc*100:.2f}%", f"{cnn_acc*100:.2f}%"]
})

print(summary.to_string(index=False))