# -*- coding: utf-8 -*-
"""Assignment6_TomoGAN_Denoising.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nKtyl7UnUsYBp-XXQgCKVsIoGVNJDRbO

# WEEK 6 - DATA 56000
## Assignment #6: TomoGAN for Scientific Image Denoising
**Pol Monne Parera (L30170743)**  
pmonneparera@lewisu.edu  
Spring 2026

Generative Adversarial Network (TomoGAN) for denoising real scientific images.

### 1. Imports
"""

import os
import time
import shutil
from pathlib import Path
from urllib.request import urlretrieve

import h5py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

try:
    from skimage.metrics import peak_signal_noise_ratio, structural_similarity
    SKIMAGE_AVAILABLE = True
except Exception:
    SKIMAGE_AVAILABLE = False

np.random.seed(42)
tf.random.set_seed(42)

def _make_legacy_initializer_compatible(base_initializer):
    class LegacyCompatInitializer(base_initializer):
        @classmethod
        def from_config(cls, config):
            config = dict(config)
            config.pop('dtype', None)
            return cls(**config)
    LegacyCompatInitializer.__name__ = base_initializer.__name__
    return LegacyCompatInitializer

LEGACY_CUSTOM_OBJECTS = {
    name: _make_legacy_initializer_compatible(getattr(tf.keras.initializers, name))
    for name in [
        'GlorotUniform', 'Zeros', 'Ones', 'RandomNormal',
        'RandomUniform', 'TruncatedNormal', 'Orthogonal', 'Constant'
    ]
    if hasattr(tf.keras.initializers, name)
}

"""### 2. Download Dataset and Pre-trained Model"""

DATA_DIR = Path('dataset')
MODEL_DIR = Path('model')
OUTPUT_DIR = Path('outputs')

for directory in [DATA_DIR, MODEL_DIR, OUTPUT_DIR]:
    if directory.exists():
        shutil.rmtree(directory)
    directory.mkdir(parents=True, exist_ok=True)

DATASET_URL = 'https://raw.githubusercontent.com/AIScienceTutorial/Denoising/main/dataset/demo-dataset-real4test.h5'
MODEL_URL = 'https://raw.githubusercontent.com/AIScienceTutorial/Denoising/main/model/TomoGAN.h5'

dataset_path = DATA_DIR / 'demo-dataset-real4test.h5'
model_path = MODEL_DIR / 'TomoGAN.h5'

def download_if_needed(url, destination):
    if destination.exists():
        print(f'Already exists: {destination}')
    else:
        print(f'Downloading {destination.name} ...')
        urlretrieve(url, destination)
        print(f'Saved to: {destination}')

download_if_needed(DATASET_URL, dataset_path)
download_if_needed(MODEL_URL, model_path)

"""### 3. Load and Inspect the Scientific Image Dataset"""

with h5py.File(dataset_path, 'r') as h5fd:
    ns_img_test_real = h5fd['test_ns'][:]
    gt_img_test_real = h5fd['test_gt'][:]

print(f'Noisy test set shape: {ns_img_test_real.shape}')
print(f'Ground-truth test set shape: {gt_img_test_real.shape}')
print(f'Dtype: {ns_img_test_real.dtype}')
print(f'Noisy intensity range: [{ns_img_test_real.min():.3f}, {ns_img_test_real.max():.3f}]')
print(f'GT intensity range: [{gt_img_test_real.min():.3f}, {gt_img_test_real.max():.3f}]')

fig, axes = plt.subplots(2, 2, figsize=(10, 10))
for i in range(2):
    axes[i, 0].imshow(ns_img_test_real[i], cmap='gray')
    axes[i, 0].set_title(f'Noisy input #{i}')
    axes[i, 0].axis('off')

    axes[i, 1].imshow(gt_img_test_real[i], cmap='gray')
    axes[i, 1].set_title(f'Ground truth #{i}')
    axes[i, 1].axis('off')

plt.suptitle('Real Scientific Test Images: Noisy vs Ground Truth', fontsize=12)
plt.tight_layout()
plt.savefig(OUTPUT_DIR / 'raw_vs_gt_examples.png', dpi=140, bbox_inches='tight')
plt.show()

"""### 4. Load the Pre-trained TomoGAN Model"""

TomoGAN_mdl = tf.keras.models.load_model(
    model_path,
    custom_objects=LEGACY_CUSTOM_OBJECTS,
    compile=False,
)
TomoGAN_mdl.summary()

"""### 5. Denoise the Test Images"""

def show_triplet(noisy_img, clean_img, denoised_img, index, crop=(200, -100, 200, -100)):
    top, bottom, left, right = crop
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    axes[0].imshow(noisy_img[top:bottom, left:right], cmap='gray')
    axes[0].set_title('Noisy / Input', fontsize=14)
    axes[1].imshow(clean_img[top:bottom, left:right], cmap='gray')
    axes[1].set_title('Clean / Label', fontsize=14)
    axes[2].imshow(denoised_img[top:bottom, left:right], cmap='gray')
    axes[2].set_title('Denoised / Output', fontsize=14)
    for ax in axes:
        ax.axis('off')
    plt.suptitle(f'TomoGAN qualitative comparison #{index}', fontsize=15)
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f'tomogan_triplet_{index}.png', dpi=140, bbox_inches='tight')
    plt.show()

denoised_examples = []
for idx in range(min(4, ns_img_test_real.shape[0])):
    denoised_img = TomoGAN_mdl.predict(ns_img_test_real[idx:idx+1, :, :, np.newaxis], verbose=0).squeeze()
    denoised_examples.append(denoised_img)
    show_triplet(ns_img_test_real[idx], gt_img_test_real[idx], denoised_img, idx)
print(f'Saved {len(denoised_examples)} qualitative comparison figures to {OUTPUT_DIR.resolve()}')

"""### 6. Batch Inference Timing"""

batch_sz = len(ns_img_test_real)
tick = time.time()
batch_denoised = TomoGAN_mdl.predict(
    ns_img_test_real[:batch_sz, :, :, np.newaxis],
    verbose=0
).squeeze()
elapsed = time.time() - tick

print(f'Batch size: {batch_sz}')
print(f'Image size: {ns_img_test_real.shape[1]} x {ns_img_test_real.shape[2]}')
print(f'Total inference time: {elapsed:.2f} seconds')
print(f'Average time per image: {elapsed / batch_sz:.2f} seconds')
print(f'Batch output shape: {batch_denoised.shape}')

"""### 7. Quantitative Metrics"""

metric_rows = []

for idx in range(batch_sz):
    noisy = ns_img_test_real[idx].astype(np.float32)
    clean = gt_img_test_real[idx].astype(np.float32)
    denoised = batch_denoised[idx].astype(np.float32)

    data_range = float(clean.max() - clean.min())
    if data_range == 0:
        data_range = 1.0

    row = {
        "Sample": idx,
        "MSE noisy->gt": np.mean((noisy - clean) ** 2),
        "MSE denoised->gt": np.mean((denoised - clean) ** 2),
        "MAE noisy->gt": np.mean(np.abs(noisy - clean)),
        "MAE denoised->gt": np.mean(np.abs(denoised - clean)),
        "PSNR noisy->gt": peak_signal_noise_ratio(clean, noisy, data_range=data_range),
        "PSNR denoised->gt": peak_signal_noise_ratio(clean, denoised, data_range=data_range),
        "SSIM noisy->gt": structural_similarity(clean, noisy, data_range=data_range),
        "SSIM denoised->gt": structural_similarity(clean, denoised, data_range=data_range),
    }

    metric_rows.append(row)

metrics_df = pd.DataFrame(metric_rows)
display(metrics_df.round(4))

print("Average metrics:")
display(metrics_df.drop(columns=["Sample"]).mean().to_frame("Mean").T.round(4))

"""### 8. Summary Comparison"""

improvement_summary = pd.DataFrame({
    "Metric": ["MSE", "MAE", "PSNR", "SSIM"],
    "Noisy Mean": [
        metrics_df["MSE noisy->gt"].mean(),
        metrics_df["MAE noisy->gt"].mean(),
        metrics_df["PSNR noisy->gt"].mean(),
        metrics_df["SSIM noisy->gt"].mean(),
    ],
    "Denoised Mean": [
        metrics_df["MSE denoised->gt"].mean(),
        metrics_df["MAE denoised->gt"].mean(),
        metrics_df["PSNR denoised->gt"].mean(),
        metrics_df["SSIM denoised->gt"].mean(),
    ]
})

display(improvement_summary.round(4))